city_timezone_map = {
    "Albuquerque": "US/Mountain",
    "Anaheim": "US/Pacific",
    "Anchorage": "US/Alaska",
    "Arlington": "US/Central",
    "Atlanta": "US/Eastern",
    "Aurora": "US/Mountain",
    "Austin": "US/Central",
    "Bakersfield": "US/Pacific",
    "Baltimore": "US/Eastern",
    "Boston": "US/Eastern",
    "Buffalo": "US/Eastern",
    "Chandler": "US/Mountain",
    "Charlotte": "US/Eastern",
    "Chicago": "US/Central",
    "Chula Vista": "US/Pacific",
    "Cincinnati": "US/Eastern",
    "Cleveland": "US/Eastern",
    "Colorado Springs": "US/Mountain",
    "Columbus": "US/Eastern",
    "Corpus Christi": "US/Central",
    "Dallas": "US/Central",
    "Denver": "US/Mountain",
    "Detroit": "US/Eastern",
    "Durham": "US/Eastern",
    "El Paso": "US/Mountain",
    "Fort Wayne": "US/Eastern",
    "Fort Worth": "US/Central",
    "Fresno": "US/Pacific",
    "Gilbert": "US/Mountain",
    "Glendale": "US/Mountain",
    "Greensboro": "US/Eastern",
    "Henderson": "US/Pacific",
    "Honolulu": "Pacific/Honolulu",
    "Houston": "US/Central",
    "Indianapolis": "US/Eastern",
    "Irvine": "US/Pacific",
    "Jacksonville": "US/Eastern",
    "Jersey City": "US/Eastern",
    "Kansas City": "US/Central",
    "Laredo": "US/Central",
    "Las Vegas": "US/Pacific",
    "Lexington": "US/Eastern",
    "Lincoln": "US/Central",
    "Long Beach": "US/Pacific",
    "Los Angeles": "US/Pacific",
    "Louisville": "US/Eastern",
    "Lubbock": "US/Central",
    "Madison": "US/Central",
    "Memphis": "US/Central",
    "Mesa": "US/Mountain",
    "Miami": "US/Eastern",
    "Milwaukee": "US/Central",
    "Minneapolis": "US/Central",
    "Nashville": "US/Central",
    "New Orleans": "US/Central",
    "New York": "US/Eastern",
    "Newark": "US/Eastern",
    "Oakland": "US/Pacific",
    "Oklahoma City": "US/Central",
    "Omaha": "US/Central",
    "Orlando": "US/Eastern",
    "Philadelphia": "US/Eastern",
    "Phoenix": "US/Mountain",
    "Pittsburgh": "US/Eastern",
    "Plano": "US/Central",
    "Portland": "US/Pacific",
    "Raleigh": "US/Eastern",
    "Reno": "US/Pacific",
    "Riverside": "US/Pacific",
    "Sacramento": "US/Pacific",
    "San Antonio": "US/Central",
    "San Diego": "US/Pacific",
    "San Francisco": "US/Pacific",
    "San Jose": "US/Pacific",
    "Santa Ana": "US/Pacific",
    "Scottsdale": "US/Mountain",
    "Seattle": "US/Pacific",
    "St. Louis": "US/Central",
    "St. Paul": "US/Central",
    "St. Petersburg": "US/Eastern",
    "Stockton": "US/Pacific",
    "Tampa": "US/Eastern",
    "Toledo": "US/Eastern",
    "Tucson": "US/Mountain",
    "Tulsa": "US/Central",
    "Virginia Beach": "US/Eastern",
    "Washington": "US/Eastern",
    "Wichita": "US/Central",
    "Winston-Salem": "US/Eastern",
}